### ISSUE TITLE
Any chance to get that adapted for the serial (RS485) connection?

### ISSUE THREAD

**Issue by riogrande75** [jblance/jkbms#3]
Do you plan to add the option for grabbing data from this device via the serial RS485 port?
The batteries are installed in a garden shed, BT is out of range. But there is a IP connection available.
Hooking up the RS485 port on a USR TCP232 serial2eth converter would allow me to communicate to the device over IP easily.

**Comment by jblance** [comment]
Its possible, although this code is pretty BLE specific, ie it is BLE
commands that are sent, received and decoded.

I would need to determine the serial command set to make any progress.

I am currently integrating this with the mppsolar code to make a more
generic solution with a variety of protocol handlers (including serial and
ble), so if the serial commands are found we'd be able to make it work
between the 2.

An alternative would be a raspberry pi in the battery shed talking BLE to
the BMS and IP back to the house

**Comment by riogrande75** [comment]
Well, commands seem to be very identical to the ones sent via BT (off course).
Here the protocol description:
[http://www.mediafire.com/file/1bvfggecz5l2nba/JK-B1A24S-RS485-protocol-english.pdf/file](url)

**Comment by jblance** [comment]
ok ive added this to the mpp-solar codebase, so that should allow serial comms to a JK BMS
nothing to test with, so there may be some bugs that need resolving
so with the latest mppsolar (0.7.9 or later) something like
```mpp-solar -p /dev/XXX -b 9600 -P JK485 -D``` should try to talk to the JKBMS over rs485 (after chnaging /dev/XXX to the correct port)

**Comment by jblance** [comment]
Closing this here - open an issue in the other repo for any issues with the mpp-solar rs485 code
